### ISSUE TITLE
about CODA Error from coda_open()

### ISSUE THREAD

**Issue by StarsTravel** [stcorp/coda#102]
I'm opening a .N1 file of GOMOS with coda_open:
filename='I:\GOM_EXT_2P_20060501_21786\GOM_EXT_2PRFIN20060501_012926_000000392047_00189_21786_9419.N1';
pf2 = coda_open(filename);
product_type = coda_product_type(pf2);

but I'm getting the following problem:
错误使用 coda_matlab
CODA Error

出错 coda_open (第 17 行)
[varargout{1:max(1,nargout)}] = coda_matlab('OPEN',varargin{:});

出错 main (第 55 行)
pf2 = coda_open(filename);
 
![image](https://github.com/stcorp/coda/assets/25655034/b7d807ac-8bca-459a-b5ad-7d00145592f5)

In fact, yesterday I was able to use functions such as coda_open normally.
What went wrong?
[GOM_EXT_2PRFIN20060501_012926_000000392047_00189_21786_9419.zip](https://github.com/user-attachments/files/16043325/GOM_EXT_2PRFIN20060501_012926_000000392047_00189_21786_9419.zip)

**Comment by svniemeijer** [comment]
The product seems ok. I think the problem is that coda couldn't find the codadef file for GOMOS anymore.
Make sure to locally store a copy of the [codadef file](https://github.com/stcorp/codadef-envisat-gomos/releases/tag/ENVISAT_GOMOS-20121004) and put it in the `share/coda/definition` folder of your coda installation as described in the [CODA MATLAB documentation](http://stcorp.github.io/coda/doc/html/matlab/index.html#codadef).
You can also put it in a different location and create a `CODA_DEFINITION` global environment variable to point to the directory where your stored the codadef file.

**Comment by StarsTravel** [comment]
Thank you !!!!
















At 2024-07-01 00:12:03, "Sander Niemeijer" ***@***.***> wrote:

The product seems ok. I think the problem is that coda couldn't find the codadef file for GOMOS anymore.
Make sure to locally store a copy of the codadef file and put it in the share/coda/definition folder of your coda installation as described in the CODA MATLAB documentation.
You can also put it in a different location and create a CODA_DEFINITION global environment variable to point to the directory where your stored the codadef file.
