### ISSUE TITLE
[MIPAS] coda.time_double_to_parts_utc can't manage the conversion of the date in the right way

### ISSUE THREAD

**Issue by flaviobar** [stcorp/coda#11]
```
coda.time_double_to_parts(0.0)
[2000, 1, 1, 0, 0, 0, 0]

coda.time_double_to_parts_utc(0.0)
[1999, 12, 31, 23, 59, 28, 0]
```
Since the reference time of coda output is 2000-1-1,  this 2 functions should return the same time for 0.0 s. 
2 seconds likely should take into account the leap seconds: during the MIPAS mission the insertion of a leap second occurred only 2 times (2005-12-31 and 2008-12-31).

**Comment by svniemeijer** [comment]
Interestingly, we recently added a better clarification on this topic in the documentation. Please have a look at https://github.com/stcorp/coda/blob/master/libcoda/coda-time.c

The important part is: "In CODA, the choice was made to base the offset for the TAI floating point values on the convention that 2000-01-01T00:00:00 UTC has an offset of 0 (in UTC). Since at that time TAI was 32 seconds ahead of UTC, coda_utcdatetime_to_double() (which converts UTC to TAI) will thus return the value 32 for 2000-01-01T00:00:00."

**Comment by flaviobar** [comment]
According to me, in this way CODA is changing the reference time. If you get a time (as example with coda.fetch), this time (without inserted leap seconds) is written as second since 2000-1-1 UTC. In the MIPAS file this time is stored with 3 integer (# of day,# sec from beginning of the day, # microseconds) and these values are related to the 2000-1-1 UTC.
Did you add 32 seconds to the value obtained from the MIPAS file when you get the time? 
If not, time_double_to_parts should return the time corresponding to this amount of seconds without the leap second, and time_double_to_parts_utc should return the the right utc time corresponding to this amount of seconds.
```
coda.time_double_to_parts(0.0)
[2000, 1, 1, 0, 0, 0, 0]
coda.time_double_to_parts_utc(0.0)
[2000, 1, 1, 0, 0, 0, 0]
coda.time_double_to_parts(189388800.0)
[2006, 1, 1, 0, 0, 0, 0]
coda.time_double_to_parts_utc(189388800.0)
[2005, 12, 31, 23, 59, 60, 0]
coda.time_double_to_parts(189388801.0)
[2000, 1, 1, 0, 0, 1, 0]
coda.time_double_to_parts(189388801.0)
[2000, 1, 1, 0, 0, 0, 0]
```

**Comment by svniemeijer** [comment]
It is a bit more complicated. The algorithm most people use is one where each day has 86400 seconds. If you don't do this, and you are close to midnight, then the leap seconds can introduce a change of date. Instead of requiring people to always properly deal with leap seconds when converting a CODA time value back to a date, we went for simplicity. See also the comment for 'time' in http://stcorp.nl/coda/doc/codadef/codadef-format.html.
Instead, if a user really wants to be leap second precise, we do provide some functions to allow this, but you will have to do more work yourself. For instance, you can disable the automatic conversion to time by setting coda.set_option_perform_conversions(0). In that case you will get the MIPAS time value as a record of 3 integers and you can perform any time conversion you want yourself.
However, be aware that ENVISAT time values are not fully leap second accurate either. You have to take care of https://earth.esa.int/handbooks/ra2-mwr/CNTR2-8-2.html as well if you want to be precise.
