### ISSUE TITLE
coda indexing in python interface is confusing and inconsistent

### ISSUE THREAD

**Issue by jdkloe** [stcorp/coda#40]
When using the code interface in python3 I have several issues with indexing.
For my testing I used an Aeolus L2B product file and matching CODADEF file (simply because I am most familiar with that product as I developed it myself). Extracting single values with fetch works as intended:
``` python
import coda
coda.version()
fn = 'AE_TEST_ALD_U_N_2B_20181002T001000_20181002T001136_0001.DBL'
fh = coda.open(fn)
coda.fetch(fh, 'meas_map', 0, 'mie_map_of_l1b_meas_used', 0, 'which_l2b_wind_id')
```
gives the expected output of:
'2.19'
1

Also replacing the data selection by a single string works fine:
``` python
coda.fetch(fh, 'meas_map[0]/mie_map_of_l1b_meas_used[0]/which_l2b_wind_id')
```

However, extracting this data set as 2D array only works for the first form:
``` python
data = coda.fetch(fh, 'meas_map', 0, 'mie_map_of_l1b_meas_used', -1, 'which_l2b_wind_id')
data.shape
```
this gives the expected output of:
(24,)

But this does not work:
``` python
data = coda.fetch(fh, 'meas_map[0]/mie_map_of_l1b_meas_used[-1]/which_l2b_wind_id') 
```
It gives me this error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/people/matlab/.local/lib/python3.7/site-packages/coda/codapython.py", line 652, in fetch
    (intermediateNode,pathIndex) = _traverse_path(cursor,path)
  File "/usr/people/matlab/.local/lib/python3.7/site-packages/coda/codapython.py", line 185, in _traverse_path
    cursor_goto(cursor,path[pathIndex])
codac.CodacError: coda_cursor_goto(): array index (-1) exceeds array range [0:24)

Additional remarks / feature requests:
* the use of the value -1 to get the full array is very confusing in python. This value in python usually gives you the last item of an array or list. I would suggest  to also allow the special value ':' in the python interface to extract the full array.
* there is no way to do slicing. coda only allows extracting a single number or the full array. Especially for large files getting the full array can take a very long time, and calling coda fetch inside a nested for loop to extract a partial 2D array, can take even longer. I would suggest to implement a mechanism similar to the slice known in python. I.e. '[5:10]' would give you array elements with index values 5 up to, but not including 10.

**Comment by svniemeijer** [comment]
The important thing to consider here is that we are dealing with a python wrapping of a C interface.

The C interface itself does not support the ```-1``` style operation to group individually read values into a single target array.
This functionality is implemented purely in Python (but also in the IDL and MATLAB interfaces of CODA).
The coda.fetch() is actually a Python function that internally constructs a CODA cursor and then navigates through the product to read the elements that are requested.

There exists partial-read functionality of arrays within the CODA C library, but this is limited to offset+length range specification and only works on arrays of scalars.

Especially if you are running into performance problems, knowing about the lower level CODA Python functions and how CODA cursors work will be rather important.

Also be aware that the AEOLUS products are internally structured very differently from e.g. hdf/netcdf files in that they combine fields from the same measurement close together instead of combining all instances of a single field close together. This means that multidimensional array slicing, which is a common approach for hdf/netcdf, is just intrinsically not feasible for products such as the AEOLUS products.

With CODA cursors you can still relatively efficiently get the data out of the product. The [aux_met_12.py](https://github.com/stcorp/coda-examples/blob/master/python/aeolus/aux_met_12.py) example that is online provides a nice showcase of this.
If you have specific cases that you want assistance with (in terms of how to best optimise it) then let us know by sending an email to coda@stcorp.nl.

An important thing to remember is that each parameter passed to ```coda.fetch()``` is handled as follows:
- it is translated to a ```coda.cursor_goto(cursor, path)``` if it is a string (which can only navigate to a single position, so it doesn't support ranges)
- it is translated to a ```coda.cursor_goto_array_element_by_index(cursor, index)``` if it is a non-negative number
- when you pass ```-1`` as parameter then ```coda.fetch()``` will internally just use a python for-loop in which a CODA cursor is run over all elements (and the results as combined into single array)

Whatever position the cursor points to at the end of the list of parameters is read recursively into a python structure (e.g. a ```coda.fetch(fh)``` will read the whole product and a ```coda.fetch(fh, "mph")``` will read the whole MPH).

In other words, ```coda.fetch()``` is not doing things any more efficiently than you can do yourself with cursors. It is just a function that provides some wrapping around all of this to make it a bit easier.

If we want to make things consistent as you request then as far as I can see it, this can only be done in three ways, and none of them are preferable in my opinion:
- removing the option to provide ```-1``` as parameter
- allow the C library to support ranged reads as in ```"foo[5:6]/bar[3:4]/bla"```; this requires that we construct complete data trees within the C domain and then translate that to Python, which would require a huge change to the C library
- support the ```-1``` inside a ```"meas_map[0]/mie_map_of_l1b_meas_used[-1]/which_l2b_wind_id"``` and have this split into a 
```["meas_map[0]/mie_map_of_l1b_meas_used", -1, "which_l2b_wind_id"]``` sequence of parameters by ```coda.fetch()``` itself; however this would break the current simple rule that a string parameter is always passed directly to a ```coda.cursor_goto()``` (so we would just be replacing one potential point of confusion with another)

**Comment by jdkloe** [comment]
Thanks for your explanations. Based on this, I don\'t think it is needed to change the code as such, but I think the documentation can be improved. My answers:

   * I hope you agree that the difference between 
     ("meas_map[0]/mie_map_of_l1b_meas_used[-1]/which_l2b_wind_id)
     and
     ("meas_map[0]/mie_map_of_l1b_meas_used", -1, "which_l2b_wind_id")
    is not clear to (python) users at the moment. A user would have to have knowledge about the internals of the code to know this. The current html documentation included in the project does not give information on this, and does not make clear the the fetch function is in fact coded in python. Maybe somewhere else information on the web can be found, but that was not obvious to me. So I suggest that an explanation on data selection (or cursor setting) is added  and that the python specific description of fetch is modified to make clear that the -1 option only is python specific, only works if it is not included in the string, and that  the looping is still done in python and not in the c-code (so a clear disclaimer that fetch() is only for user convenience and does not make data access faster).

   * as for using the lower level interface. The current split in documentation in high and low level functions is fine, but it probably has as consequence that users read only the high level part. As long as the code works for the intended purpose this is no problem, but if it means users will not use more efficient ways of reading large files this may be something to reconsider. 
Also thanks for your pointer to the aux_met_12.py example script. Actually I overlooked your collection of example scripts completely since I did not expect it to be in a different git repository. There is not a single reference to this example collection on the main documentation page at https://github.com/stcorp/coda/blob/master/doc/html/index.html
So I would suggest to add a reference there to the coda-examples repository, and it may be useful as well to add links from the language specific interface start pages to the language specific examples. So on https://github.com/stcorp/coda/blob/master/doc/html/python/index.html include a link to https://github.com/stcorp/coda-examples/tree/master/python etc.

* on the last issue of indexing, yes I know that the coda library is based on c-code and that the python library is just a wrapper around it. The python ways of indexing and slicing differ from what is usual in other languages so that makes it difficult to adapt to the python specifics and to keep the code simple at the same time. So now that it is clear that fetch is a python specific function and not implemented in c, I don't think adapting its ways is needed.

**Comment by svniemeijer** [comment]
I agree that we could improve the documentation some more regarding the '-1' behaviour. I will see what can be done here.

In the mean time, we are also working on a new website for the atmospheric toolbox (which includes coda) and as part of that we also plan to make examples and tutorials more accessible. This new website should become available somewhere later this year.

**Comment by yika64** [comment]
I download Aeolus data includes:AE_OPER_ALD_U_N_2B_20201008T233259_20201009T010347_0001.DBL  and AE_OPER_ALD_U_N_2B_20201008T233259_20201009T010347_0001.HDR. When I run:

`product=coda.open("AE_OPER_ALD_U_N_2B_20201008T233259_20201009T010347_0001.DBL")`

it gives the error:
`coda_open(): unsupported product file`

But it is available to open the .HDR data:
`pf=coda.open("AE_OPER_ALD_U_N_2B_20190628T234623_20190629T011435_0003.HDR")`

Could you please deal with it? 3q!

**Comment by svniemeijer** [comment]
Please make sure you installed the [codadef](http://github.com/stcorp/codadef-aeolus/releases/latest), by putting that file into the share/coda/definitions subdirectory of your coda installation.

Since the .HDR is plain XML, coda will always open that file. But without a codadef it will treat all fields as strings. You will need the codadef to interpret all information correctly (e.g. interpret time values and integer/float values).

**Comment by svniemeijer** [comment]
Also, please raise such questions on [our forum](https://forum.atmospherictoolbox.org) and not in issues like this that deal with something totally different.

**Comment by svniemeijer** [comment]
a small paragraph on this was added to the Python documentation
