### ISSUE TITLE
Problem when installing coda 2.21 with ./configure on MacOS 10.14.6

### ISSUE THREAD

**Issue by quitcaz** [stcorp/coda#41]
Installation process with ./configure breaks down with error : 
"checking the archiver (ar) interface... unknown
configure: error: could not determine ar interface"

**Comment by quitcaz** [comment]
[config.log](https://github.com/stcorp/coda/files/3635209/config.log)

if I run ar (for example ar -r arch_test file1.txt file2.txt) : it says: 'creating archive arch_test'

**Comment by svniemeijer** [comment]
The log file complains with the following:
```
configure:4666: ar cru libconftest.a conftest.o >&5
/opt/local/bin/ranlib: object: libconftest.a(conftest.o) malformed object (unknown load command 1)
ar: internal ranlib command failed
```

I am not sure what is going on (I am also building CODA on macOS 10.14.6 and without problems).

I assume you are using MacPorts (due to the /opt/local paths)? But this is something I am also using myself, so that is probably not the problem.

Could you maybe check that the ranlib tool on your system works correctly?
For me this is in `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib`, but yours is likely at `/Library/Developer/CommandLineTools/usr/bin/ranlib`.

Is your MacPorts and Xcode up-to-date?

**Comment by svniemeijer** [comment]
(what I forget to add, is to check your system ranlib, by removing/disabling the ranlib from /opt/local/bin)

**Comment by quitcaz** [comment]
OK thanks
I tried to run macport and it said there was a platform mismatch so I'll start with that...

**Comment by svniemeijer** [comment]
Closing issue as there was no further feedback.
