### ISSUE TITLE
Install python bindings via pypi

### ISSUE THREAD

**Issue by mir06** [stcorp/coda#42]
Are there any plans to make the python bindings available on pypi? I know there is already another project with the same name and also some similar project names are assigned.

It would be very comfortable to install the bindings using pip (e.g. in a virtual environment) while the C-library is installed by the system's package manager.  `libcoda-dev` is in Debian buster.

**Comment by svniemeijer** [comment]
At the moment there are no such plans. The problem is that there is a too tight dependency between the python binding and the C library.
The python binding requires a specific swig binary module, which is currently generated via the autotools/cmake build system and not via a setup.py.

For Debian they seem to have made the python3 interface for coda already available as a separate package, so the python bindings are available there already.

If you want a virtualised environment that contains coda, we highly recommend using conda.
With conda you can actually properly manage the dependencies of python packages against C-library dependencies.
The conda packages for coda are available via our [stcorp channel](https://anaconda.org/stcorp/coda).

**Comment by mir06** [comment]
@svniemeijer thank you very much for the prompt answer.

Yes with Debian buster there is the `python3-coda` package and conda surely works as well. But I need it with `virtualenv`.

Thus we will stay with compiling by ourself.
